### PR TITLE
Fixes URL processing for named external and internal links

### LINKED ISSUE #3: Named internal links after normal links are mangled
Example. The following tiddler:

> ```This is a test tiddler that features an [[internal link]] followed by another [[different link]] and then by a [[third one|named link]], then by some random text that really doesn't matter at all. If we throw a named link here [[like this|another named link]] it's fine, but a named link after a [[normal link]] will be ruined. This tiddler gets mangled by the regular expressions. ```

... is, when processed, mangled, producing the following output:

> ```This is a test tiddler that features an [internal link]] followed by another [different link](#different%20link) and then by a [third one](named link), then by some random text that really doesn't matter at all. If we throw a named link here [like this](another named link) it's fine, but a named link after a [[normal link](#third%20one%5D%28named%20link%29%2C%20then%20by%20some%20random%20text%20that%20really%20doesn%27t%20matter%20at%20all.%20If%20we%20throw%20a%20named%20link%20here%20%5Blike%20this%5D%28another%20named%20link%29%20it%27s%20fine%2C%20but%20a%20named%20link%20after%20a%20%5B%5Bnormal%20link) will be ruined. This tiddler gets mangled by the regular expressions. ```

The cause is a missing `\]` in the named internal link regex. PR coming right up.

### PR DESCRIPTION
**Pull request by LumosX**
Fixes #3.

With this PR, the test tiddler (fortified with external links)
> ```This is a test tiddler that features an [[internal link]] followed by another [[different link]] and then by a [[third one|named link]], then by some random text that really doesn't matter at all. If we throw a named link here [[like this|another named link]] it's fine, but a named link after a [[normal link]] will be ruined. This tiddler gets mangled by the regular expressions. For good measure, we'll throw in some URLs, like this: [[https://github.com]] or why not [[a named tiddlywiki url|https://tiddlywiki.com]]? We'll intersperse them with a few more [[internal link]]s and another  external [[https://github.com]] just to be safe, before we end with the same [[named url with a different name|https://tiddlywiki.com]].```

... is now processed to
> ```This is a test tiddler that features an [internal link](#internal%20link) followed by another [different link](#different%20link) and then by a [third one](#named%20link), then by some random text that really doesn't matter at all. If we throw a named link here [like this](#another%20named%20link) it's fine, but a named link after a [normal link](#normal%20link) will be ruined. This tiddler gets mangled by the regular expressions. For good measure, we'll throw in some URLs, like this: <https://github.com> or why not [a named tiddlywiki url](https://tiddlywiki.com)? We'll intersperse them with a few more [internal link](#internal%20link)s and another  external <https://github.com> just to be safe, before we end with the same [named url with a different name](https://tiddlywiki.com).```

... which appears to fix the mangling.

Note that the regexes matching against http(s) will still fail for all other protocols, but that's out of scope of this PR (and I personally don't have a use case for supporting that).

### CODE REVIEW

**Comment by MaxGyver83** [comment]
Thank you! But there is at least one regression:

In one of my `.tid` files, I have this link:

```
[[[dev] Is there a text editor following the UNIX philosophy?|http://lists.suckless.org/dev/2202/34655.html]]
```

Before, it was correctly translated to:

```md
[[dev] Is there a text editor following the UNIX philosophy?](http://lists.suckless.org/dev/2202/34655.html)
```

With your branch, it becomes:

```md
[[[dev] Is there a text editor following the UNIX philosophy?|<http://lists.suckless.org/dev/2202/34655.html>]]
```

**Comment by LumosX** [comment]
Great catch, I didn't realise square brackets could appear anywhere in links, even in internal ones. I figured I might as well go the whole hog and fix it, so here goes. With this commit, the following example:

> ```Testing [[internal link]] and [[different link]] and [[third one|named link]] and [[https://github.com]], and [[like this|another named link]] and [[normal link]] and a [[[prefixed] internal link]] and  and [[a named URL|https://tiddlywiki.com]] with [[internal link]] and [[[dev] Is there a text editor following the UNIX philosophy?|http://lists.suckless.org/dev/2202/34655.html]] followed by another [[[longer prefix] internal link]] and [[ftp://user:pass@server.com]] just to be safe, before we end with the same [[[prefixed] named url with a different protocol|ftp://ftplink.net]].```

... becomes:
> ```Testing [internal link](#internal%20link) and [different link](#different%20link) and [third one](#named%20link) and <https://github.com>, and [like this](#another%20named%20link) and [normal link](#normal%20link) and a [[prefixed] internal link](#%5Bprefixed%5D%20internal%20link) and  and [a named URL](https://tiddlywiki.com) with [internal link](#internal%20link) and [[dev] Is there a text editor following the UNIX philosophy?](http://lists.suckless.org/dev/2202/34655.html) followed by another [[longer prefix] internal link](#%5Blonger%20prefix%5D%20internal%20link) and <ftp://user:pass@server.com> just to be safe, before we end with the same [[prefixed] named url with a different protocol](ftp://ftplink.net).```

As a side effect, we now support all protocols as well. The URL detection mechanism is rather naïve, but I'm ought to be serviceable.

Personally, I'd still rather use `[](#target)` for internal links instead of duplicating the label, but that's out of scope of this PR... and is what #6 is about. :P

**Comment by LumosX** [comment]
Corrected the is_external check to no longer treat "www." URLs as URLs, because markdown doesn't do it and thus neither should we.

**Review by MaxGyver83 — APPROVED** [review]
Great! This fixes also two broken links in my (not yet migrated) tiddlers. Thank you!

**Comment by LumosX** [comment]
Cheers mate, just happy to help.

**Pull request merged**
